### ISSUE TITLE
how to change long press

### ISSUE THREAD

**Issue by Carbone13** [hugocbpassos/drag_select_grid_view#6]
hi , is there any settings to change longPress selection on grid to onTap selection ? thank you

**Comment by hugocbpassos** [comment]
I'm not sure I understand you. Would you mind further elaborating?

**Comment by Carbone13** [comment]
my mean , i want to change button controller on long press to selecting , into just tapping and no need wait long press to select . I hope that you understand my mean .

**Comment by hugocbpassos** [comment]
I see. Seems like an usual behavior. Can you give me a practical example where this makes sense?

**Comment by dungnv2602** [comment]
I guess he is referring to this 
![Screenshot_20200307-165630_My Files](https://user-images.githubusercontent.com/19910775/76141244-e4e72000-6094-11ea-86f5-2009a52b3d9c.jpg)
It woyld be awesome if this is achievable

**Comment by hugocastelani** [comment]
Currently, this library requires you to long-press to start "selection mode". When you are in "selection mode", every item you tap gets selected. From my understand, the feature you are looking for is a way to start "selection mode" without having to previously long-press.

@Carbone13 @dungnv2602 Is that correct?

**Comment by dungnv2602** [comment]
In my perspective, the main issue which this package is trying to solve is able to select multiple grid items along with the first item selected to the next item user dragging up/down to. 
If changing selecting items to onTap, a scenario like above doesn't make sense anymore.
So we should respect onLongPress, don't change it.

**Comment by hugocbpassos** [comment]
@dungnv2602 I must agree, therefore I'm closing this for now.
